### ISSUE TITLE
[Bug Report] spam in the console

### ISSUE THREAD

**Issue by vHWhiiz** [Crazy-Crew/Crazy-Envoy#53]
**Describe the bug**
An error message spam my console.

**Versions (please complete the following information):**
 - Minecraft Server Version: [e.g. 1.16.1]
 - Plugin Version: [e.g. 1.3.10]

**Pastebin any errors in console**
Link: https://pastebin.com/NLUzCC0Q

**Comment by badbones69** [comment]
Newest version should fix issues.
