### ISSUE TITLE
[Bug Report] Holographic Displays + CrazyEnvoy = Broken (On Latest Verisons of MC)

### ISSUE THREAD

**Issue by VanillaChan6571** [Crazy-Crew/Crazy-Envoy#56]
**Describe the bug**

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.3
 - Plugin Version: 1.3.10-RELEASE

*Do **NOT** say Latest use `/version crazyenvoy` in the console.

**Pastebin any errors in console**
Link: none.

**Issue**
No Holographic Displays show during Envoy on later versions of minecraft.

**Screenshots**
https://i.imgur.com/kSlvJpk.png

**Comment by badbones69** [comment]
Works as of current builds.
