### ISSUE TITLE
[Suggestion] Support Decent Holograms 

### ISSUE THREAD

**Issue by MrTokyo12345** [Crazy-Crew/Crazy-Envoy#59]
Support Decent Holograms 
Spigot link: https://www.spigotmc.org/resources/decent-holograms-1-8-1-18-papi-support-no-dependencies.96927/

**Comment by ItzSave** [comment]
This is a very needed feature.

**Comment by badbones69** [comment]
Added: e72c195a514ade43b70e61ee83bea5d1cd3ba723
