### ISSUE TITLE
Maven repo doesn't include latest version

### ISSUE THREAD

**Issue by Phoenix616** [Crazy-Crew/Crazy-Envoy#60]
The maven repo at https://nexus.badbones69.com/ seems to only include v1.3.10 making it harder to use the changed API package of 1.3.13 (also not sure why it was necessary to break that in the first place...)

**Comment by badbones69** [comment]
Sorry about that. It slips my mind to upload the newest versions to nexus. I need to try and make sure to remember to do this. I just pushed the newest version to it.
