### ISSUE TITLE
[Suggestion] Make time letters editable.

### ISSUE THREAD

**Issue by Sparkaxd** [Crazy-Crew/Crazy-Envoy#62]
I have a suggestion on the leaderboard, I want placeholder texts in Turkish, can you help me? I want the Turkish version.

Change this: 
![167167655-d7f7d421-ab3c-40c5-88c2-41af4e14bc88](https://user-images.githubusercontent.com/104910551/167168575-f06d3dfa-0779-4267-96e8-cac167011661.png)

To this:
![2022-05-06 (19)](https://user-images.githubusercontent.com/104910551/167168837-93fb6126-157a-48c9-b9ad-ffd9ee32a1e8.png)

**Comment by Sparkaxd** [comment]
![2022-05-06 (19)](https://user-images.githubusercontent.com/104910551/167168837-93fb6126-157a-48c9-b9ad-ffd9ee32a1e8.png)

i want to do the same

**Comment by badbones69** [comment]
Added: 4837db05ea5c5608321428a2f3c3489ba817b8d9
